package main

import "fmt"

func main(){

	num1 := 33
	fmt.Println(fib(num1))

}

func fib(num1 int) int {
	counter:=0
	if num1 == 1 || num1 == 2 {
		return 1;
	} else {
		result := fib(num1 - 1) + fib(num1 - 2)
		if result%2==0{
			counter=counter + result
		}

		return counter;
	}
}


/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.*/